id: P006696
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03940
  title: གསུང་འབུམ། བྱམས་པ་འབྱུང་གནས།
  author: ''
  volumes:
    1f711f8150eb46db944d164567af2495:
      image_group_id: I00KG03942
      title: ''
      volume_number: 1
      total_pages: 502
    76394569e4d7488f94878103b909cdc8:
      image_group_id: I00KG03943
      title: ''
      volume_number: 2
      total_pages: 534
    0935f3a6897e4d9d999249bdc02e77a6:
      image_group_id: I00KG03944
      title: ''
      volume_number: 3
      total_pages: 592
    b5ebcb45b6254381a4a1b98f0e38f5ea:
      image_group_id: I00KG03945
      title: ''
      volume_number: 4
      total_pages: 578
    a7dc19060c7d4c9aa7952442cd2474f2:
      image_group_id: I00KG03946
      title: ''
      volume_number: 5
      total_pages: 474
    76864d99911e45bea73a74c4d1aa9082:
      image_group_id: I00KG03947
      title: ''
      volume_number: 6
      total_pages: 402
