id: I33B33B6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:47:40+00:00'
last_modified: '2022-06-08T06:12:56.715889+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03940
  title: གསུང་འབུམ། བྱམས་པ་འབྱུང་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DBAA:
      image_group_id: I00KG03942
      title: ''
      total_pages: 502
      order: 1
      base_file: DBAA.txt
    EBD7:
      image_group_id: I00KG03943
      title: ''
      total_pages: 534
      order: 2
      base_file: EBD7.txt
    '1814':
      image_group_id: I00KG03944
      title: ''
      total_pages: 592
      order: 3
      base_file: 1814.txt
    A2BC:
      image_group_id: I00KG03945
      title: ''
      total_pages: 578
      order: 4
      base_file: A2BC.txt
    0C8D:
      image_group_id: I00KG03946
      title: ''
      total_pages: 474
      order: 5
      base_file: 0C8D.txt
    A4BF:
      image_group_id: I00KG03947
      title: ''
      total_pages: 402
      order: 6
      base_file: A4BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
