id: I33B33B6C
legacy_id: P006696
ocr_import_info:
  bdrc_scan_id: W00KG03940
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T12:44:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:29:50.611848+00:00'
last_modified: 2022-08-30 21:33:55.311840
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03940
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03940
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བྱམས་པ་འབྱུང་གནས།
  author: རི་བོ་ཆེ་རྗེ་དྲུང་བྱམས་པ་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.918077141603776
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG03946:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03946
      total_pages: 474
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00KG03946.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9087065655573654
    legacy_id: v005
  I00KG03945:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03945
      total_pages: 578
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00KG03945.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8881733131089923
    legacy_id: v004
  I00KG03944:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03944
      total_pages: 592
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00KG03944.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9434260745983676
    legacy_id: v003
  I00KG03942:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03942
      total_pages: 502
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03942.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9375113028997675
    legacy_id: v001
  I00KG03947:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03947
      total_pages: 402
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00KG03947.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9022440019360043
    legacy_id: v006
  I00KG03943:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03943
      total_pages: 534
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG03943.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9294036996642924
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
